version: "3.8"

services:

  db:
    image: 'postgres:13'
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: library
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres_db:/var/lib/postgresql/data
      - ./postgres/custom-config.conf:/var/lib/postgresql/data/postgresql.conf # SHOW config_file;
      - ./postgres/custom_pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf # SHOW hba_file; SHOW ALL;
    networks:
      - shop-network
    ports:
      - "5432:5432"

  django:
    build: ./shop
    ports:
      - "8000:8000"
    volumes:
      - ./shop:/app
    environment:
      - POSTGRES_NAME=library
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=pass
    networks:
      - shop-network
    depends_on:
      - db

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: pass
    networks:
      - shop-network
    depends_on:
      - db

volumes:
  postgres_db:

networks:
  shop-network:
    name: shop-network
