version: "3.8"

services:

  pinot-controller:
    image: apachepinot/pinot:0.10.0
    command: "StartController -zkAddress zookeeper:2181"
    container_name: "pinot-controller"
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - $PWD/pinot/config:/config
    depends_on:
      - zookeeper
    networks:
      - shop-network

  pinot-broker:
    image: apachepinot/pinot:0.10.0
    command: "StartBroker -zkAddress zookeeper:2181"
    restart: unless-stopped
    container_name: "pinot-broker"
    ports:
      - "8099:8099"
    volumes:
      - $PWD/pinot/config:/config
    depends_on:
      - pinot-controller
    networks:
      - shop-network

  pinot-server:
    image: apachepinot/pinot:0.10.0
    container_name: "pinot-server"
    command: "StartServer -zkAddress zookeeper:2181"
    restart: unless-stopped
    volumes:
      - $PWD/pinot/config:/config
    depends_on:
      - pinot-broker
    networks:
      - shop-network

networks:
  shop-network:
    name: shop-network
